New CPC approac

diff --git a/runtime b/runtime
--- a/runtime
+++ b/runtime
@@ -1,13 +1,4 @@
 #!/usr/bin/env bash
-##############################################
-# SWARM = Shell Wrapper and Runtime Modifier #
-# Author:	Simon Arjuna Erat (sea)	     #
-# License:	GPL v2			     #
-# Copyleft:	1995-2021		     #
-# Created:	2020.01.18		     #
-# Changed:	2021.03.16	 	     #
-# Build:	67			     #
-##############################################
 #
 #	SWARM is the successor of TUI (Text User Interace)
 #	It is an interface between script authors and end users.
@@ -47,71 +38,117 @@
 # * Optionaly, you may pass SWARM_RAMDISK_DIR=/path/to/mountpoint
 ##############################################
 #
+# Clear certain env and other variables
+#
+	${DEBUG:-false} && set -x
+	# shellcheck disable=SC2086,SC2184
+	unset SWARM[@] ${!SWARM_DIR_*} IFS >/dev/zero
+	declare -A SWARM
+#
+#	    ---   Datasheet   ---
+#
+#################################################
+# SWARM = Shell Wrapper and Runtime Modifier	#
+# Author:	Simon Arjuna Erat (sea)		#
+SWARM[LICENSE]="GPLv2"	# License: ./docs/GPLv2	#
+# Idea:		1995				#
+# Copyleft:	2011-2021			#
+# Created:	2020.01.18			#
+# Changed:	2021.03.19	 		#
+SWARM[VERSION]=0.9
+SWARM[BUILD]=68
+SWARM[GIT]="http://github.com/sri-arjuna/SWARM"
+SWARM[ISSUES]="${SWARM[GIT]}/issues"
+#################################################
+#
 # Version Check
 #
 	if [[ -z ${BASH_VERSINFO[@]} ]] || [[ ${BASH_VERSINFO[0]} -lt 4  ]]
-	then	# Print error of no BASH variables where found
+	then	# Print error if no BASH variables were found
 		# Or if BASH version is too low
 		printf '%s\n' "Requires BASH 4.3 or higher"
-		return || exit
+		return 2>/dev/zero || exit
 	else	# Bash version seems is 4 or higher
 		if [[ 4 -eq ${BASH_VERSINFO[0]} ]]
 		then 	# Major matches
 			if [[ ${BASH_VERSINFO[1]} -lt 3  ]]
 			then	# Minor does not
 				printf '%s\n' "Requires BASH 4.3 or higher"
-				return || exit
+				# At least that is where I can guarantue it works as promised.
+				return 2>/dev/zero || exit
 			fi
 		fi
 	fi
 #
 # Core Public Variables
 #
-	# SWARM
-	${DEBUG:-false} && set -x
-	# shellcheck disable=SC2086 disable=SC2184
-	unset SWARM[@] ${!SWARM_DIR_*} IFS >/dev/zero
-	declare -A SWARM
-	# isSWARMfirstTime will be set to false if SWARMRC (~/.swarmrc) is found
-	isSWARMfirstTime=true
-	#echo $hasCOLUMNS;exit
-	SWARM[VERSION]=0.9
-	SWARM[BUILD]=67
-	SWARM[AUTHOR]="Simon Arjuna Erat (sea)"
-	SWARM[GIT]="http://github.com/sri-arjuna/swarm"
-	SWARM[LICENSE]="GPLv2"
 	# This is default 'highlighted' MACHINE or ROOT display
 	# Non-root users (if existing) have very hardcoded 'default-blue' (fallback) theme
 	SWARM[THEME]="default-red"
-	SWARM[ROOTDIR]=""
+	# This refers to the location of this file
+	# You can spee up the process by passing: SWARMDIR=
+	SWARM[ROOTDIR]="$SWARMDIR"
 	# Language must be pre-set up until the basic language file was loaded
 	SWARM[LANG]="en_GB"
 	SWARM_CODE=$$
+	# isSWARMfirstTime will be set to false if SWARMRC (~/.swarmrc) is found
+	isSWARMfirstTime=true
+
 #
-# Set first time default
+# Cross Platform Compatibility (CPC)
 #
-#	This is just ment as failsafe if PATH is not set
-#	to get the most elementary basics on/of most default systems
-	posix_PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
-	configure_PATH="$BINDIR:$SBINDIR"
-	os_PATH=":$OS_DIR_BIN:$OS_DIR_SBIN"
-	# Exporting an empty variable, but if it is, it will be filled with the current path.
-	PATH_OLD="${PATH_OLD:-$PATH}"
-	# Use current PATH or if empty, default POSIX path, and append additional cross over paths
-	# Might result in double entries if this file is source multiple times without properly
-	# clearing the ENV by the use of swarm.cleanup
-	PATH="${PATH:-$posix_PATH}:$configure_PATH:$os_PATH"
-	# Make sure TERM is set
+# There are hints on:
+# * https://community.unix.com/t/tip-template-for-a-safe-and-portable-script/375171
+# But I'm ignoring  the recomended language setting, since SWARM scripts do support different languages,
+# and does already a specific LC_ALL=C before 'system' calls it parses.
+	# Exporting an empty variable, but if it is, it will be filled with the current path. (they are mis-spelled on purpose!)
+	# This is used in swarm.cleanup to restore the env if this file was sourced
+	# Lets add an appending : so we restore to a non-path env as (if) it were
+	PATH_ORGINAL="${PATH_ORGINAL:-$PATH:}"
+	PWD_ORGINAL=="${PWD_ORGINAL:-${PWD:-$(pwd)}}"
+	# HP-UX is Posix-compliant with
+	export UNIX95=
+	# GREP_OPTIONS can obscure GNU grep
+	unset GREP_OPTIONS
+	# LD_* can obscure external commands
+	unset LD_LIBRARY_PATH LD_PRELOAD
+	# no glob file-matching in command args and word lists (for loop)
+#	set -f
+	# Unix optional packages install in
+	opt_path="/usr/local/bin:/usr/local/sbin"
+	solaris_opt_path="/usr/sfw/bin:/opt/csw/bin"
+	# Catch if we are 'within' a 'configure' env
+	[[ -n "$BINDIR$SBINDIR"  ]] && configure_PATH="$BINDIR:$SBINDIR"
+	# Catch other seen variables...
+	[[ -n "$OS_DIR_BIN$OS_DIR_SBIN"  ]] && os_PATH=":$OS_DIR_BIN:$OS_DIR_SBIN"
+	# These are the most basic places to look for executables
+	# Since the usr-move, it is prefered to first look for those directories
+	posix_PATH="/usr/bin:/usr/sbin:/bin:/sbin"
+	# Create a new PATH based on existing templates
+	path_new="/usr/xpg4/bin:/usr/ucb"
+	# After all, users might have taken their time to provide required/desired path attributes to their ENV..
+	# Lets make sure they do not get forgotton, just handle those as last... ;)
+	for elem in $(sed s,":","\n",g -- <<< "${posix_PATH}:${opt_path}:${configure_PATH}:${os_PATH}:${PATH}" )
+	do
+		[[ :"$path_new": != *:"$elem":* ]] && \
+			path_new+=":$elem"
+	done
+	# set PATH so no PATH is inherited, export it to all children
+	PATH="$path_new" ; unset path_new
+	export PATH
+	# Check if we need special treatment
 	[[ -n "$SSH_CLIENT" ]] && isSSH=true || isSSH=false
+	# Make sure TERM is set
 	TERM="${TERM:-GNU_Linux}"
-	if [[ "" == "${TERM/GNU_Linux}" ]] || [[ "dumb" == "${TERM}" ]]
-	then	echo "
-You are within a 'limited' SSH session - no regular ENV is set.
-It is recomended to use: 'ssh -t user@host', not -T.
-"
+	# Check if it were empty or even worse, if we are in a 'dumb' TERM...
+	# And of course, if we idenfity ourself already as SSH_Client, then of course we have to go there!
+	if [[ "dumb" == "${TERM}" ]] || [[ "" == "${TERM/GNU_Linux}" ]] || $isSSH
+	then	# Lets fix term to something useful
 		TERM="xterm"
 		# This is required to work within a SSH env
 		export TERM
+		# If there were another reason we have a restricted session
+		# Lets just reuse this for the same purpose - for now... (because its the only reason I know of!)
 		isSSH=true
 		# Skip selection if COLUMNS are preset
 		if [[ -z "$COLUMNS" ]]
@@ -121,16 +158,19 @@ It is recomended to use: 'ssh -t user@host', not -T.
 			export COLUMNS
 		fi
 	fi
-#
-# Handle COLUMNS after TERM
-# This is to avoid 80 COlUMNS screens in a ssh -T session 190 COLUMNS window.
+	# This is to avoid 80 COlUMNS screens in a ssh -T session while the screen is a 190 COLUMNS window.
 	# hasCOLUMNS is for internal use only
 	if [[ -n "$COLUMNS" ]]
-	then	hasCOLUMNS=true
+	then	# We want this to applied even - well specialy - within a SSH env
+		# because if the SSH terminal requires us to set a specific width
+		# - there wont be a way to idenfity the proper width of the screen/tty.
+		hasCOLUMNS=true
 	else	# This is still required, So swarm.update.geometry will update the value
 		# to adjust to terminal window changes - that otherwise (hasColumns=true)
 		# would happen automatically, or be forced to a specific width
 		hasCOLUMNS=false
+		# This is now invoked for a first value
+		# swarm.update.geometry will update this value every given intervall automatically
 		COLUMNS=$(tput cols)
 	fi
 	# Most basic commands ; do not change (But pre-set these variables in the shell for first use)!
@@ -170,9 +210,9 @@ It is recomended to use: 'ssh -t user@host', not -T.
 	# shellcheck disable=SC2155
 	export -r PRINTABLE_LESSER="$(${ECHO:-echo} -e \\u003c)" 2&>/dev/zero
 #
-# Some other things
+# Date pre-formatting
 #
-	# Need to get these updating them self upon call
+	# Need to get these updating them self upon call, like: $($DATE_TIME_LOG)
 	# Use these to set the date variable: `
 	export DATE_TODAY="$DATE +%F"
 	export DATE_TIME="$DATE +%T"
@@ -217,10 +257,10 @@ It is recomended to use: 'ssh -t user@host', not -T.
 		if [[ -f "${SWARMDIR}/runtime" ]]
 		then	# Assign the variable
 			SWARM[ROOTDIR]="$SWARMDIR"
-		else	# This is the only hardcoded 'english only' message
+		else	# This is the last hardcoded 'english only' message
 			$PRINTF '%s\n' "Fatal, provided SWARMDIR=$SWARMDIR dir not found - assumed: \"${SWARM[ROOTDIR]}\" and you are in ${PWD:-$(${PWD_EXEC})}."
 			sleep 3
-			return 1
+			return 1 || exit 1
 		fi
 	fi
 #
@@ -247,7 +287,7 @@ It is recomended to use: 'ssh -t user@host', not -T.
 	for lang_file in "$SWARM_DIR_LANG/en_GB"/*.lang
 	do
 		# shellcheck disable=SC1090
-		source "$lang_file" 2>/dev/zero	# Sadly, some strings cause issues as they rely on functions that are not yet loaded
+		source "$lang_file" ## 2>/dev/zero	# Sadly, some strings cause issues as they rely on functions that are not yet loaded
 		$PRINTF "."
 	done
 #
@@ -554,18 +594,71 @@ It is recomended to use: 'ssh -t user@host', not -T.
 			sysinfo)
 				pre='swarm\.sysinfo\.'
 				list=$(	declare | $GREP "$pre" | $AWK '/\(\)/ {print $1}' | $GREP -v ^"_" )
-				cur="" last="x"
+				toplevels=$($AWK -F. '{print $3}' <<< "$list"|uniq)
 			# Output
 				header --default "$SWARM_MSG_WORD_SYSTEM $SWARM_MSG_WORD_INFORMATION"
+				for section in $toplevels
+				do
+					header "" "$section" ""
+					#title "$($ECHO $(swarm.sysinfo.$section 2>/dev/zero || $ECHO $section))"
+					subs=$($GREP "$section"  <<< "$list" | $AWK -F '.' '{print $4}'|uniq)
+					tasks=""
+					for s in $subs
+					do
+						if $GREP -q "${section}\.${s}\." <<< "$list"
+						then	last+=" $s"
+						else	first+=" $s"
+						fi
+					done
+					tasks="$first $last"
+					for sub in $tasks
+					do
+						if $GREP -q "${section}\.${sub}\." <<< "$list"
+						then
+							title "$sub"
+						fi
+						for l in $($GREP "\.${section}\." <<< "$list" | $GREP "$sub")
+						do
+							printe "$l" "$($ECHO $($l))"
+						done
+					done
+				done
+
+				exit
+
 				for ls in $list
 				do
-					cur="${ls/$pre/}"
-					cur=${cur/\.*}
-					if [[ ! "$cur" == "$last" ]]
-					then	title "${cur}"
-						last="$cur"
-					fi
-					printe "$ls:" "$(echo $($ls))"
+					# Basics
+					base="${ls/$pre/}"		# Remove the prefix: swarm.sysinfo.
+					toplevel=${base/\.*}		# Remove everything after the first dot (.), should be: os, hw, net
+					item="${base/*\.}"		# Remove everything before the last dot (.)
+					# Now subsections, like: os.version, hw.audio or net.ssh
+					checkval=${base/$toplevel}	# Remove the toplevel
+					checkval=${checkval/$item}	# And the last item
+					checkval=${checkval/\.}		# Any remaining dots
+
+
+					echo "T$toplevel - i$item " # 		\t\t B$base - "
+				#	if [[ ! "$item" == "$toplevel" ]]
+				#	then	# item and toplevel are different,
+						# so lets compare them
+
+						# Lets handle toplevel sections: hw, os
+						if [[ ! "$toplevel" == "$tlast" ]]
+						then	header "" "$toplevel" ""
+							title "$item"
+							tlast="$toplevel"
+						fi
+
+						# Lets see if there is a subsection:
+						if [[ -n "${checkval}" ]]  && [[ ! "$checkval" == "$ilast" ]]
+						then	title "${checkval}"
+							ilast="${checkval}"
+						fi
+				#	else	header "" "$toplevel" ""
+				#		title "$item : $(swarm.sysinfo.$base)"
+				#	fi
+					printe "$ls:" "$($ECHO $($ls))"
 				done
 				;;
 			esac
